/*
Transfers API

API version: 3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package transfers

import (
    "github.com/adyen/adyen-go-api-library/v6/src/common"
)

// APIClient manages communication with the Transfers API API v3
// In most cases there should be only one, shared, APIClient.
type APIClient struct {
	common common.Service // Reuse a single struct instead of allocating one for each service on the heap.

	// API Services

	GeneralApi *GeneralApi
}

// NewAPIClient creates a new API client. Requires a userAgent string describing your application.
// optionally a custom http.Client to allow for advanced features such as caching.
func NewAPIClient(client *common.Client) *APIClient {
	c := &APIClient{}
    c.common.Client = client
    c.common.BasePath = func() string {
        return client.Cfg.TransfersEndpoint
    }

	// API Services
	c.GeneralApi = (*GeneralApi)(&c.common)

	return c
}