/*
Management API

API version: 3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package management

import (
	"encoding/json"
	"time"

	"github.com/adyen/adyen-go-api-library/v21/src/common"
)

// checks if the InstalledAPKs type satisfies the MappedNullable interface at compile time
var _ common.MappedNullable = &InstalledAPKs{}

// InstalledAPKs struct for InstalledAPKs
type InstalledAPKs struct {
	// The date and time when the app was installed.
	ConfirmationDate *time.Time `json:"confirmationDate,omitempty"`
	// The package name of the app.
	PackageName *string `json:"packageName,omitempty"`
	// The version name of the app.
	VersionName *string `json:"versionName,omitempty"`
}

// NewInstalledAPKs instantiates a new InstalledAPKs object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInstalledAPKs() *InstalledAPKs {
	this := InstalledAPKs{}
	return &this
}

// NewInstalledAPKsWithDefaults instantiates a new InstalledAPKs object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInstalledAPKsWithDefaults() *InstalledAPKs {
	this := InstalledAPKs{}
	return &this
}

// GetConfirmationDate returns the ConfirmationDate field value if set, zero value otherwise.
func (o *InstalledAPKs) GetConfirmationDate() time.Time {
	if o == nil || common.IsNil(o.ConfirmationDate) {
		var ret time.Time
		return ret
	}
	return *o.ConfirmationDate
}

// GetConfirmationDateOk returns a tuple with the ConfirmationDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstalledAPKs) GetConfirmationDateOk() (*time.Time, bool) {
	if o == nil || common.IsNil(o.ConfirmationDate) {
		return nil, false
	}
	return o.ConfirmationDate, true
}

// HasConfirmationDate returns a boolean if a field has been set.
func (o *InstalledAPKs) HasConfirmationDate() bool {
	if o != nil && !common.IsNil(o.ConfirmationDate) {
		return true
	}

	return false
}

// SetConfirmationDate gets a reference to the given time.Time and assigns it to the ConfirmationDate field.
func (o *InstalledAPKs) SetConfirmationDate(v time.Time) {
	o.ConfirmationDate = &v
}

// GetPackageName returns the PackageName field value if set, zero value otherwise.
func (o *InstalledAPKs) GetPackageName() string {
	if o == nil || common.IsNil(o.PackageName) {
		var ret string
		return ret
	}
	return *o.PackageName
}

// GetPackageNameOk returns a tuple with the PackageName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstalledAPKs) GetPackageNameOk() (*string, bool) {
	if o == nil || common.IsNil(o.PackageName) {
		return nil, false
	}
	return o.PackageName, true
}

// HasPackageName returns a boolean if a field has been set.
func (o *InstalledAPKs) HasPackageName() bool {
	if o != nil && !common.IsNil(o.PackageName) {
		return true
	}

	return false
}

// SetPackageName gets a reference to the given string and assigns it to the PackageName field.
func (o *InstalledAPKs) SetPackageName(v string) {
	o.PackageName = &v
}

// GetVersionName returns the VersionName field value if set, zero value otherwise.
func (o *InstalledAPKs) GetVersionName() string {
	if o == nil || common.IsNil(o.VersionName) {
		var ret string
		return ret
	}
	return *o.VersionName
}

// GetVersionNameOk returns a tuple with the VersionName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstalledAPKs) GetVersionNameOk() (*string, bool) {
	if o == nil || common.IsNil(o.VersionName) {
		return nil, false
	}
	return o.VersionName, true
}

// HasVersionName returns a boolean if a field has been set.
func (o *InstalledAPKs) HasVersionName() bool {
	if o != nil && !common.IsNil(o.VersionName) {
		return true
	}

	return false
}

// SetVersionName gets a reference to the given string and assigns it to the VersionName field.
func (o *InstalledAPKs) SetVersionName(v string) {
	o.VersionName = &v
}

func (o InstalledAPKs) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InstalledAPKs) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !common.IsNil(o.ConfirmationDate) {
		toSerialize["confirmationDate"] = o.ConfirmationDate
	}
	if !common.IsNil(o.PackageName) {
		toSerialize["packageName"] = o.PackageName
	}
	if !common.IsNil(o.VersionName) {
		toSerialize["versionName"] = o.VersionName
	}
	return toSerialize, nil
}

type NullableInstalledAPKs struct {
	value *InstalledAPKs
	isSet bool
}

func (v NullableInstalledAPKs) Get() *InstalledAPKs {
	return v.value
}

func (v *NullableInstalledAPKs) Set(val *InstalledAPKs) {
	v.value = val
	v.isSet = true
}

func (v NullableInstalledAPKs) IsSet() bool {
	return v.isSet
}

func (v *NullableInstalledAPKs) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstalledAPKs(val *InstalledAPKs) *NullableInstalledAPKs {
	return &NullableInstalledAPKs{value: val, isSet: true}
}

func (v NullableInstalledAPKs) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstalledAPKs) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
