/*
Management API

API version: 3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package management

import (
	"encoding/json"

	"github.com/adyen/adyen-go-api-library/v21/src/common"
)

// checks if the GirocardResponseInfo type satisfies the MappedNullable interface at compile time
var _ common.MappedNullable = &GirocardResponseInfo{}

// GirocardResponseInfo struct for GirocardResponseInfo
type GirocardResponseInfo struct {
	TransactionDescription *TransactionDescriptionResponseInfo `json:"transactionDescription,omitempty"`
}

// NewGirocardResponseInfo instantiates a new GirocardResponseInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGirocardResponseInfo() *GirocardResponseInfo {
	this := GirocardResponseInfo{}
	return &this
}

// NewGirocardResponseInfoWithDefaults instantiates a new GirocardResponseInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGirocardResponseInfoWithDefaults() *GirocardResponseInfo {
	this := GirocardResponseInfo{}
	return &this
}

// GetTransactionDescription returns the TransactionDescription field value if set, zero value otherwise.
func (o *GirocardResponseInfo) GetTransactionDescription() TransactionDescriptionResponseInfo {
	if o == nil || common.IsNil(o.TransactionDescription) {
		var ret TransactionDescriptionResponseInfo
		return ret
	}
	return *o.TransactionDescription
}

// GetTransactionDescriptionOk returns a tuple with the TransactionDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GirocardResponseInfo) GetTransactionDescriptionOk() (*TransactionDescriptionResponseInfo, bool) {
	if o == nil || common.IsNil(o.TransactionDescription) {
		return nil, false
	}
	return o.TransactionDescription, true
}

// HasTransactionDescription returns a boolean if a field has been set.
func (o *GirocardResponseInfo) HasTransactionDescription() bool {
	if o != nil && !common.IsNil(o.TransactionDescription) {
		return true
	}

	return false
}

// SetTransactionDescription gets a reference to the given TransactionDescriptionResponseInfo and assigns it to the TransactionDescription field.
func (o *GirocardResponseInfo) SetTransactionDescription(v TransactionDescriptionResponseInfo) {
	o.TransactionDescription = &v
}

func (o GirocardResponseInfo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GirocardResponseInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !common.IsNil(o.TransactionDescription) {
		toSerialize["transactionDescription"] = o.TransactionDescription
	}
	return toSerialize, nil
}

type NullableGirocardResponseInfo struct {
	value *GirocardResponseInfo
	isSet bool
}

func (v NullableGirocardResponseInfo) Get() *GirocardResponseInfo {
	return v.value
}

func (v *NullableGirocardResponseInfo) Set(val *GirocardResponseInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableGirocardResponseInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableGirocardResponseInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGirocardResponseInfo(val *GirocardResponseInfo) *NullableGirocardResponseInfo {
	return &NullableGirocardResponseInfo{value: val, isSet: true}
}

func (v NullableGirocardResponseInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGirocardResponseInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
