/*
Configuration API

API version: 2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package balanceplatform

import (
	"context"
    "net/http"
    "net/url"
    "strings"
    "github.com/adyen/adyen-go-api-library/v21/src/common"
)

// SCAAssociationManagementApi service
type SCAAssociationManagementApi common.Service

// All parameters accepted by SCAAssociationManagementApi.ApproveAssociation
type SCAAssociationManagementApiApproveAssociationInput struct {
	wWWAuthenticate *string
	approveAssociationRequest *ApproveAssociationRequest
}

// The header for authenticating through SCA.
func (r SCAAssociationManagementApiApproveAssociationInput) WWWAuthenticate(wWWAuthenticate string) SCAAssociationManagementApiApproveAssociationInput {
	r.wWWAuthenticate = &wWWAuthenticate
	return r
}

func (r SCAAssociationManagementApiApproveAssociationInput) ApproveAssociationRequest(approveAssociationRequest ApproveAssociationRequest) SCAAssociationManagementApiApproveAssociationInput {
	r.approveAssociationRequest = &approveAssociationRequest
	return r
}


/*
Prepare a request for ApproveAssociation

@return SCAAssociationManagementApiApproveAssociationInput
*/
func (a *SCAAssociationManagementApi) ApproveAssociationInput() SCAAssociationManagementApiApproveAssociationInput {
	return SCAAssociationManagementApiApproveAssociationInput{
	}
}

/*
ApproveAssociation Approve a pending approval association

Approves a previously created association that is in a pending state.

@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
@param r SCAAssociationManagementApiApproveAssociationInput - Request parameters, see ApproveAssociationInput
@return ApproveAssociationResponse, *http.Response, error
*/
func (a *SCAAssociationManagementApi) ApproveAssociation(ctx context.Context, r SCAAssociationManagementApiApproveAssociationInput) (ApproveAssociationResponse, *http.Response, error) {
    res := &ApproveAssociationResponse{}
	path := "/scaAssociations"
    queryParams := url.Values{}
    headerParams := make(map[string]string)
    common.ParameterAddToHeaderOrQuery(headerParams, "WWW-Authenticate", r.wWWAuthenticate, "")
    httpRes, err := common.SendAPIRequest(
        ctx,
        a.Client,
        r.approveAssociationRequest,
        res,
        http.MethodPatch,
        a.BasePath()+path,
        queryParams,
        headerParams,
    )

    if httpRes == nil {
        return *res, httpRes, err
    }

    var serviceError common.RestServiceError
                        if httpRes.StatusCode == 401 {
                            body, _ := ioutil.ReadAll(httpRes.Body)
                            decodeError := json.Unmarshal([]byte(body), &serviceError)
                            if decodeError != nil {
                                return *res, httpRes, decodeError
                            }
                            return *res, httpRes, serviceError
                        }
                        if httpRes.StatusCode == 403 {
                            body, _ := ioutil.ReadAll(httpRes.Body)
                            decodeError := json.Unmarshal([]byte(body), &serviceError)
                            if decodeError != nil {
                                return *res, httpRes, decodeError
                            }
                            return *res, httpRes, serviceError
                        }
                        if httpRes.StatusCode == 500 {
                            body, _ := ioutil.ReadAll(httpRes.Body)
                            decodeError := json.Unmarshal([]byte(body), &serviceError)
                            if decodeError != nil {
                                return *res, httpRes, decodeError
                            }
                            return *res, httpRes, serviceError
                        }

    return *res, httpRes, err
}


// All parameters accepted by SCAAssociationManagementApi.ListAssociations
type SCAAssociationManagementApiListAssociationsInput struct {
	entityType *ScaEntityType
	entityId *string
	pageSize *int32
	pageNumber *int32
}

// The type of entity you want to retrieve a list of associations for.   Possible values: **accountHolder** or **paymentInstrument**.
func (r SCAAssociationManagementApiListAssociationsInput) EntityType(entityType ScaEntityType) SCAAssociationManagementApiListAssociationsInput {
	r.entityType = &entityType
	return r
}

// The unique identifier of the entity.
func (r SCAAssociationManagementApiListAssociationsInput) EntityId(entityId string) SCAAssociationManagementApiListAssociationsInput {
	r.entityId = &entityId
	return r
}

// The number of items to have on a page.   Default: **5**.
func (r SCAAssociationManagementApiListAssociationsInput) PageSize(pageSize int32) SCAAssociationManagementApiListAssociationsInput {
	r.pageSize = &pageSize
	return r
}

// The index of the page to retrieve. The index of the first page is **0** (zero).   Default:  **0**.
func (r SCAAssociationManagementApiListAssociationsInput) PageNumber(pageNumber int32) SCAAssociationManagementApiListAssociationsInput {
	r.pageNumber = &pageNumber
	return r
}


/*
Prepare a request for ListAssociations

@return SCAAssociationManagementApiListAssociationsInput
*/
func (a *SCAAssociationManagementApi) ListAssociationsInput() SCAAssociationManagementApiListAssociationsInput {
	return SCAAssociationManagementApiListAssociationsInput{
	}
}

/*
ListAssociations Get a list of devices associated with an entity

Returns a paginated list of the SCA devices associated with a specific entity.

@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
@param r SCAAssociationManagementApiListAssociationsInput - Request parameters, see ListAssociationsInput
@return ListAssociationsResponse, *http.Response, error
*/
func (a *SCAAssociationManagementApi) ListAssociations(ctx context.Context, r SCAAssociationManagementApiListAssociationsInput) (ListAssociationsResponse, *http.Response, error) {
    res := &ListAssociationsResponse{}
	path := "/scaAssociations"
    queryParams := url.Values{}
    headerParams := make(map[string]string)
    if r.entityType != nil {
        common.ParameterAddToQuery(queryParams, "entityType", r.entityType, "")
    }
    if r.entityId != nil {
        common.ParameterAddToQuery(queryParams, "entityId", r.entityId, "")
    }
    if r.pageSize != nil {
        common.ParameterAddToQuery(queryParams, "pageSize", r.pageSize, "")
    }
    if r.pageNumber != nil {
        common.ParameterAddToQuery(queryParams, "pageNumber", r.pageNumber, "")
    }
    httpRes, err := common.SendAPIRequest(
        ctx,
        a.Client,
        nil,
        res,
        http.MethodGet,
        a.BasePath()+path,
        queryParams,
        headerParams,
    )

    if httpRes == nil {
        return *res, httpRes, err
    }

    var serviceError common.RestServiceError
                        if httpRes.StatusCode == 400 {
                            body, _ := ioutil.ReadAll(httpRes.Body)
                            decodeError := json.Unmarshal([]byte(body), &serviceError)
                            if decodeError != nil {
                                return *res, httpRes, decodeError
                            }
                            return *res, httpRes, serviceError
                        }
                        if httpRes.StatusCode == 401 {
                            body, _ := ioutil.ReadAll(httpRes.Body)
                            decodeError := json.Unmarshal([]byte(body), &serviceError)
                            if decodeError != nil {
                                return *res, httpRes, decodeError
                            }
                            return *res, httpRes, serviceError
                        }
                        if httpRes.StatusCode == 403 {
                            body, _ := ioutil.ReadAll(httpRes.Body)
                            decodeError := json.Unmarshal([]byte(body), &serviceError)
                            if decodeError != nil {
                                return *res, httpRes, decodeError
                            }
                            return *res, httpRes, serviceError
                        }
                        if httpRes.StatusCode == 500 {
                            body, _ := ioutil.ReadAll(httpRes.Body)
                            decodeError := json.Unmarshal([]byte(body), &serviceError)
                            if decodeError != nil {
                                return *res, httpRes, decodeError
                            }
                            return *res, httpRes, serviceError
                        }

    return *res, httpRes, err
}


// All parameters accepted by SCAAssociationManagementApi.RemoveAssociation
type SCAAssociationManagementApiRemoveAssociationInput struct {
	wWWAuthenticate *string
	removeAssociationRequest *RemoveAssociationRequest
}

// The header for authenticating through SCA.
func (r SCAAssociationManagementApiRemoveAssociationInput) WWWAuthenticate(wWWAuthenticate string) SCAAssociationManagementApiRemoveAssociationInput {
	r.wWWAuthenticate = &wWWAuthenticate
	return r
}

func (r SCAAssociationManagementApiRemoveAssociationInput) RemoveAssociationRequest(removeAssociationRequest RemoveAssociationRequest) SCAAssociationManagementApiRemoveAssociationInput {
	r.removeAssociationRequest = &removeAssociationRequest
	return r
}


/*
Prepare a request for RemoveAssociation

@return SCAAssociationManagementApiRemoveAssociationInput
*/
func (a *SCAAssociationManagementApi) RemoveAssociationInput() SCAAssociationManagementApiRemoveAssociationInput {
	return SCAAssociationManagementApiRemoveAssociationInput{
	}
}

/*
RemoveAssociation Delete association to devices

Deletes one or more SCA associations for a device.

@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
@param r SCAAssociationManagementApiRemoveAssociationInput - Request parameters, see RemoveAssociationInput
@return *http.Response, error
*/
func (a *SCAAssociationManagementApi) RemoveAssociation(ctx context.Context, r SCAAssociationManagementApiRemoveAssociationInput) (*http.Response, error) {
    var res interface{}
	path := "/scaAssociations"
    queryParams := url.Values{}
    headerParams := make(map[string]string)
    common.ParameterAddToHeaderOrQuery(headerParams, "WWW-Authenticate", r.wWWAuthenticate, "")
    httpRes, err := common.SendAPIRequest(
        ctx,
        a.Client,
        r.removeAssociationRequest,
        res,
        http.MethodDelete,
        a.BasePath()+path,
        queryParams,
        headerParams,
    )

    if httpRes == nil {
        return httpRes, err
    }

    var serviceError common.RestServiceError
                        if httpRes.StatusCode == 401 {
                            body, _ := ioutil.ReadAll(httpRes.Body)
                            decodeError := json.Unmarshal([]byte(body), &serviceError)
                            if decodeError != nil {
                                return httpRes, decodeError
                            }
                            return httpRes, serviceError
                        }
                        if httpRes.StatusCode == 403 {
                            body, _ := ioutil.ReadAll(httpRes.Body)
                            decodeError := json.Unmarshal([]byte(body), &serviceError)
                            if decodeError != nil {
                                return httpRes, decodeError
                            }
                            return httpRes, serviceError
                        }
                        if httpRes.StatusCode == 500 {
                            body, _ := ioutil.ReadAll(httpRes.Body)
                            decodeError := json.Unmarshal([]byte(body), &serviceError)
                            if decodeError != nil {
                                return httpRes, decodeError
                            }
                            return httpRes, serviceError
                        }

    return httpRes, err
}

