/*
Configuration API

API version: 2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package balanceplatform

import (
	"encoding/json"
    "github.com/adyen/adyen-go-api-library/v20/src/common"
)

// checks if the BalanceWebhookSettingsResponse type satisfies the MappedNullable interface at compile time
var _ common.MappedNullable = &BalanceWebhookSettingsResponse{}

// BalanceWebhookSettingsResponse struct for BalanceWebhookSettingsResponse
type BalanceWebhookSettingsResponse struct {
	// The list of settings and criteria for triggering the [balance webhook](https://docs.adyen.com/api-explorer/balance-webhooks/latest/post/balancePlatform.balanceAccount.balance.updated).
	Conditions []Condition `json:"conditions,omitempty"`
}

// NewBalanceWebhookSettingsResponse instantiates a new BalanceWebhookSettingsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBalanceWebhookSettingsResponse(currency string, id string, status string, target Target, type_ SettingType) *BalanceWebhookSettingsResponse {
	this := BalanceWebhookSettingsResponse{}
	this.Currency = currency
	this.Id = id
	this.Status = status
	this.Target = target
	this.Type = type_
	return &this
}

// NewBalanceWebhookSettingsResponseWithDefaults instantiates a new BalanceWebhookSettingsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBalanceWebhookSettingsResponseWithDefaults() *BalanceWebhookSettingsResponse {
	this := BalanceWebhookSettingsResponse{}
	return &this
}

// GetConditions returns the Conditions field value if set, zero value otherwise.
func (o *BalanceWebhookSettingsResponse) GetConditions() []Condition {
	if o == nil || common.IsNil(o.Conditions) {
		var ret []Condition
		return ret
	}
	return o.Conditions
}

// GetConditionsOk returns a tuple with the Conditions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BalanceWebhookSettingsResponse) GetConditionsOk() ([]Condition, bool) {
	if o == nil || common.IsNil(o.Conditions) {
		return nil, false
	}
	return o.Conditions, true
}

// HasConditions returns a boolean if a field has been set.
func (o *BalanceWebhookSettingsResponse) HasConditions() bool {
	if o != nil && !common.IsNil(o.Conditions) {
		return true
	}

	return false
}

// SetConditions gets a reference to the given []Condition and assigns it to the Conditions field.
func (o *BalanceWebhookSettingsResponse) SetConditions(v []Condition) {
	o.Conditions = v
}

func (o BalanceWebhookSettingsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BalanceWebhookSettingsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !common.IsNil(o.Conditions) {
		toSerialize["conditions"] = o.Conditions
	}
	return toSerialize, nil
}

type NullableBalanceWebhookSettingsResponse struct {
	value *BalanceWebhookSettingsResponse
	isSet bool
}

func (v NullableBalanceWebhookSettingsResponse) Get() *BalanceWebhookSettingsResponse {
	return v.value
}

func (v *NullableBalanceWebhookSettingsResponse) Set(val *BalanceWebhookSettingsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBalanceWebhookSettingsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBalanceWebhookSettingsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBalanceWebhookSettingsResponse(val *BalanceWebhookSettingsResponse) *NullableBalanceWebhookSettingsResponse {
	return &NullableBalanceWebhookSettingsResponse{value: val, isSet: true}
}

func (v NullableBalanceWebhookSettingsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBalanceWebhookSettingsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}



