/*
 * Adyen Checkout API
 *
 * Adyen Checkout API provides a simple and flexible way to initiate and authorise online payments. You can use the same integration for payments made with cards (including 3D Secure), mobile wallets, and local payment methods (for example, iDEAL and Sofort).  This API reference provides information on available endpoints and how to interact with them. To learn more about the API, visit [online payments documentation](https://docs.adyen.com/online-payments).  ## Authentication Each request to Checkout API must be signed with an API key. For this, [get your API key](https://docs.adyen.com/development-resources/api-credentials#generate-api-key) from your Customer Area, and set this key to the `X-API-Key` header value, for example:  ``` curl -H \"Content-Type: application/json\" \\ -H \"X-API-Key: YOUR_API_KEY\" \\ ... ``` ## Versioning Checkout API supports [versioning](https://docs.adyen.com/development-resources/versioning) using a version suffix in the endpoint URL. This suffix has the following format: \"vXX\", where XX is the version number.  For example: ``` https://checkout-test.adyen.com/v70/payments ```  ## Going live  To access the live endpoints, you need an API key from your live Customer Area.  The live endpoint URLs contain a prefix which is unique to your company account, for example: ``` https://{PREFIX}-checkout-live.adyenpayments.com/checkout/v70/payments ```  Get your `{PREFIX}` from your live Customer Area under **Developers** > **API URLs** > **Prefix**.  When preparing to do live transactions with Checkout API, follow the [go-live checklist](https://docs.adyen.com/online-payments/go-live-checklist) to make sure you've got all the required configuration in place.  ## Release notes Have a look at the [release notes](https://docs.adyen.com/online-payments/release-notes?integration_type=api&version=70) to find out what changed in this version!
 *
 * API version: 70
 * Contact: developer-experience@adyen.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package checkout

// AdditionalDataLevel23 struct for AdditionalDataLevel23
type AdditionalDataLevel23 struct {
	// Customer code, if supplied by a customer.  Encoding: ASCII.  Max length: 25 characters.  > Required for Level 2 and Level 3 data.
	EnhancedSchemeDataCustomerReference string `json:"enhancedSchemeData.customerReference,omitempty"`
	// Destination country code.  Encoding: ASCII.  Max length: 3 characters.
	EnhancedSchemeDataDestinationCountryCode string `json:"enhancedSchemeData.destinationCountryCode,omitempty"`
	// The postal code of a destination address.  Encoding: ASCII.  Max length: 10 characters.  > Required for American Express.
	EnhancedSchemeDataDestinationPostalCode string `json:"enhancedSchemeData.destinationPostalCode,omitempty"`
	// Destination state or province code.  Encoding: ASCII.Max length: 3 characters.
	EnhancedSchemeDataDestinationStateProvinceCode string `json:"enhancedSchemeData.destinationStateProvinceCode,omitempty"`
	// Duty amount, in minor units.  For example, 2000 means USD 20.00.  Max length: 12 characters.
	EnhancedSchemeDataDutyAmount string `json:"enhancedSchemeData.dutyAmount,omitempty"`
	// Shipping amount, in minor units.  For example, 2000 means USD 20.00.  Max length: 12 characters.
	EnhancedSchemeDataFreightAmount string `json:"enhancedSchemeData.freightAmount,omitempty"`
	// Item commodity code.  Encoding: ASCII.  Max length: 12 characters.
	EnhancedSchemeDataItemDetailLineItemNrCommodityCode string `json:"enhancedSchemeData.itemDetailLine[itemNr].commodityCode,omitempty"`
	// Item description.  Encoding: ASCII.  Max length: 26 characters.
	EnhancedSchemeDataItemDetailLineItemNrDescription string `json:"enhancedSchemeData.itemDetailLine[itemNr].description,omitempty"`
	// Discount amount, in minor units.  For example, 2000 means USD 20.00.  Max length: 12 characters.
	EnhancedSchemeDataItemDetailLineItemNrDiscountAmount string `json:"enhancedSchemeData.itemDetailLine[itemNr].discountAmount,omitempty"`
	// Product code.  Encoding: ASCII.  Max length: 12 characters.
	EnhancedSchemeDataItemDetailLineItemNrProductCode string `json:"enhancedSchemeData.itemDetailLine[itemNr].productCode,omitempty"`
	// Quantity, specified as an integer value.  Value must be greater than 0.  Max length: 12 characters.
	EnhancedSchemeDataItemDetailLineItemNrQuantity string `json:"enhancedSchemeData.itemDetailLine[itemNr].quantity,omitempty"`
	// Total amount, in minor units.  For example, 2000 means USD 20.00.  Max length: 12 characters.
	EnhancedSchemeDataItemDetailLineItemNrTotalAmount string `json:"enhancedSchemeData.itemDetailLine[itemNr].totalAmount,omitempty"`
	// Item unit of measurement.  Encoding: ASCII.  Max length: 3 characters.
	EnhancedSchemeDataItemDetailLineItemNrUnitOfMeasure string `json:"enhancedSchemeData.itemDetailLine[itemNr].unitOfMeasure,omitempty"`
	// Unit price, specified in [minor units](https://docs.adyen.com/development-resources/currency-codes).  Max length: 12 characters.
	EnhancedSchemeDataItemDetailLineItemNrUnitPrice string `json:"enhancedSchemeData.itemDetailLine[itemNr].unitPrice,omitempty"`
	// Order date. * Format: `ddMMyy`  Encoding: ASCII.  Max length: 6 characters.
	EnhancedSchemeDataOrderDate string `json:"enhancedSchemeData.orderDate,omitempty"`
	// The postal code of a \"ship-from\" address.  Encoding: ASCII.  Max length: 10 characters.
	EnhancedSchemeDataShipFromPostalCode string `json:"enhancedSchemeData.shipFromPostalCode,omitempty"`
	// Total tax amount, in minor units.  For example, 2000 means USD 20.00.  Max length: 12 characters.  > Required for Level 2 and Level 3 data.
	EnhancedSchemeDataTotalTaxAmount string `json:"enhancedSchemeData.totalTaxAmount,omitempty"`
}
