/*
Capital API

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package capital

import (
	"encoding/json"
    "github.com/adyen/adyen-go-api-library/v21/src/common"
)

// checks if the Disbursements type satisfies the MappedNullable interface at compile time
var _ common.MappedNullable = &Disbursements{}

// Disbursements struct for Disbursements
type Disbursements struct {
	// Contains a list of all disbursements related to the specified grant.
	Disbursements []Disbursement `json:"disbursements"`
}

// NewDisbursements instantiates a new Disbursements object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDisbursements(disbursements []Disbursement) *Disbursements {
	this := Disbursements{}
	this.Disbursements = disbursements
	return &this
}

// NewDisbursementsWithDefaults instantiates a new Disbursements object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDisbursementsWithDefaults() *Disbursements {
	this := Disbursements{}
	return &this
}

// GetDisbursements returns the Disbursements field value
func (o *Disbursements) GetDisbursements() []Disbursement {
	if o == nil {
		var ret []Disbursement
		return ret
	}

	return o.Disbursements
}

// GetDisbursementsOk returns a tuple with the Disbursements field value
// and a boolean to check if the value has been set.
func (o *Disbursements) GetDisbursementsOk() ([]Disbursement, bool) {
	if o == nil {
		return nil, false
	}
	return o.Disbursements, true
}

// SetDisbursements sets field value
func (o *Disbursements) SetDisbursements(v []Disbursement) {
	o.Disbursements = v
}

func (o Disbursements) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Disbursements) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["disbursements"] = o.Disbursements
	return toSerialize, nil
}

type NullableDisbursements struct {
	value *Disbursements
	isSet bool
}

func (v NullableDisbursements) Get() *Disbursements {
	return v.value
}

func (v *NullableDisbursements) Set(val *Disbursements) {
	v.value = val
	v.isSet = true
}

func (v NullableDisbursements) IsSet() bool {
	return v.isSet
}

func (v *NullableDisbursements) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDisbursements(val *Disbursements) *NullableDisbursements {
	return &NullableDisbursements{value: val, isSet: true}
}

func (v NullableDisbursements) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDisbursements) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}



