/*
Legal Entity Management API

Testing HostedOnboardingApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package legalentity

import (
	"context"
	openapiclient "github.com/adyen/adyen-go-api-library/v6/src/legalentity"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"net/http"
	"net/http/httptest"
	"testing"
)

func Test_LegalEntity_HostedOnboardingApiService(t *testing.T) {

	var (
		username    = "n/a"
		password    = "n/a"
		env         = openapiclient.TestEnv
		mockServer  *httptest.Server
		mockRequest *http.Request
	)

	mockServer = httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		mockRequest = r
	}))
	defer mockServer.Close()

	configuration, err := openapiclient.NewConfiguration(username, password, env)
	configuration.Servers = openapiclient.ServerConfigurations{
		{
			URL:         mockServer.URL,
			Description: "Mock Server",
		},
	}

	require.Nil(t, err, "Error creating Config object")
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test HostedOnboardingApiService ListHostedOnboardingPageThemes", func(t *testing.T) {

		apiClient.HostedOnboardingApi.ListHostedOnboardingPageThemes(context.Background()).Execute()

		assert.Equal(t, "GET", mockRequest.Method)
		assert.Equal(t, "/themes", mockRequest.URL.Path)
		assert.NotEmpty(t, mockRequest.Header.Get("Authorization"))

	})

	t.Run("Test HostedOnboardingApiService GetOnboardingLinkTheme", func(t *testing.T) {

		apiClient.HostedOnboardingApi.GetOnboardingLinkTheme(context.Background(), "123").Execute()

		assert.Equal(t, "GET", mockRequest.Method)
		assert.Equal(t, "/themes/123", mockRequest.URL.Path)
		assert.NotEmpty(t, mockRequest.Header.Get("Authorization"))

	})

	t.Run("Test HostedOnboardingApiService GetLinkToAdyenhostedOnboardingPage", func(t *testing.T) {

		apiClient.HostedOnboardingApi.GetLinkToAdyenhostedOnboardingPage(context.Background(), "123").Execute()

		assert.Equal(t, "POST", mockRequest.Method)
		assert.Equal(t, "/legalEntities/123/onboardingLinks", mockRequest.URL.Path)
		assert.NotEmpty(t, mockRequest.Header.Get("Authorization"))

	})

}
