gitUserId: adyen
gitRepoId: adyen-go-api-library/v6/src
structPrefix: true
isGoSubmodule: true
additionalProperties:
  useOneOfDiscriminatorLookup: true
templateDir: ./templates/custom
files:
    api.mustache:
        destinationFilename: .go
        templateType: API
    rest_api.mustache:
        destinationFolder: ./src/management/
        destinationFilename: .go
        templateType: API
