/*
Configuration webhooks

API version: 2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package configurationwebhook

import (
	"encoding/json"

	"github.com/adyen/adyen-go-api-library/v21/src/common"
)

// checks if the WebhookTopUpCounterparty type satisfies the MappedNullable interface at compile time
var _ common.MappedNullable = &WebhookTopUpCounterparty{}

// WebhookTopUpCounterparty struct for WebhookTopUpCounterparty
type WebhookTopUpCounterparty struct {
	// The unique identifier of the transfer instrument that is the source of the funds.
	TransferInstrumentId *string `json:"transferInstrumentId,omitempty"`
}

// NewWebhookTopUpCounterparty instantiates a new WebhookTopUpCounterparty object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookTopUpCounterparty() *WebhookTopUpCounterparty {
	this := WebhookTopUpCounterparty{}
	return &this
}

// NewWebhookTopUpCounterpartyWithDefaults instantiates a new WebhookTopUpCounterparty object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookTopUpCounterpartyWithDefaults() *WebhookTopUpCounterparty {
	this := WebhookTopUpCounterparty{}
	return &this
}

// GetTransferInstrumentId returns the TransferInstrumentId field value if set, zero value otherwise.
func (o *WebhookTopUpCounterparty) GetTransferInstrumentId() string {
	if o == nil || common.IsNil(o.TransferInstrumentId) {
		var ret string
		return ret
	}
	return *o.TransferInstrumentId
}

// GetTransferInstrumentIdOk returns a tuple with the TransferInstrumentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookTopUpCounterparty) GetTransferInstrumentIdOk() (*string, bool) {
	if o == nil || common.IsNil(o.TransferInstrumentId) {
		return nil, false
	}
	return o.TransferInstrumentId, true
}

// HasTransferInstrumentId returns a boolean if a field has been set.
func (o *WebhookTopUpCounterparty) HasTransferInstrumentId() bool {
	if o != nil && !common.IsNil(o.TransferInstrumentId) {
		return true
	}

	return false
}

// SetTransferInstrumentId gets a reference to the given string and assigns it to the TransferInstrumentId field.
func (o *WebhookTopUpCounterparty) SetTransferInstrumentId(v string) {
	o.TransferInstrumentId = &v
}

func (o WebhookTopUpCounterparty) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookTopUpCounterparty) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !common.IsNil(o.TransferInstrumentId) {
		toSerialize["transferInstrumentId"] = o.TransferInstrumentId
	}
	return toSerialize, nil
}

type NullableWebhookTopUpCounterparty struct {
	value *WebhookTopUpCounterparty
	isSet bool
}

func (v NullableWebhookTopUpCounterparty) Get() *WebhookTopUpCounterparty {
	return v.value
}

func (v *NullableWebhookTopUpCounterparty) Set(val *WebhookTopUpCounterparty) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookTopUpCounterparty) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookTopUpCounterparty) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookTopUpCounterparty(val *WebhookTopUpCounterparty) *NullableWebhookTopUpCounterparty {
	return &NullableWebhookTopUpCounterparty{value: val, isSet: true}
}

func (v NullableWebhookTopUpCounterparty) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookTopUpCounterparty) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
