/*
Configuration webhooks

API version: 2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package configurationwebhook

import (
	"encoding/json"
	"time"

	"github.com/adyen/adyen-go-api-library/v21/src/common"
)

// checks if the TopUpConfigurationEventRequest type satisfies the MappedNullable interface at compile time
var _ common.MappedNullable = &TopUpConfigurationEventRequest{}

// TopUpConfigurationEventRequest struct for TopUpConfigurationEventRequest
type TopUpConfigurationEventRequest struct {
	Data TopUpWebhookData `json:"data"`
	// The environment from which the webhook originated.  Possible values: **test**, **live**.
	Environment string `json:"environment"`
	// When the event was queued.
	Timestamp *time.Time `json:"timestamp,omitempty"`
	// Type of webhook.
	Type string `json:"type"`
}

// NewTopUpConfigurationEventRequest instantiates a new TopUpConfigurationEventRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTopUpConfigurationEventRequest(data TopUpWebhookData, environment string, type_ string) *TopUpConfigurationEventRequest {
	this := TopUpConfigurationEventRequest{}
	this.Data = data
	this.Environment = environment
	this.Type = type_
	return &this
}

// NewTopUpConfigurationEventRequestWithDefaults instantiates a new TopUpConfigurationEventRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTopUpConfigurationEventRequestWithDefaults() *TopUpConfigurationEventRequest {
	this := TopUpConfigurationEventRequest{}
	return &this
}

// GetData returns the Data field value
func (o *TopUpConfigurationEventRequest) GetData() TopUpWebhookData {
	if o == nil {
		var ret TopUpWebhookData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *TopUpConfigurationEventRequest) GetDataOk() (*TopUpWebhookData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *TopUpConfigurationEventRequest) SetData(v TopUpWebhookData) {
	o.Data = v
}

// GetEnvironment returns the Environment field value
func (o *TopUpConfigurationEventRequest) GetEnvironment() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Environment
}

// GetEnvironmentOk returns a tuple with the Environment field value
// and a boolean to check if the value has been set.
func (o *TopUpConfigurationEventRequest) GetEnvironmentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Environment, true
}

// SetEnvironment sets field value
func (o *TopUpConfigurationEventRequest) SetEnvironment(v string) {
	o.Environment = v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *TopUpConfigurationEventRequest) GetTimestamp() time.Time {
	if o == nil || common.IsNil(o.Timestamp) {
		var ret time.Time
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TopUpConfigurationEventRequest) GetTimestampOk() (*time.Time, bool) {
	if o == nil || common.IsNil(o.Timestamp) {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *TopUpConfigurationEventRequest) HasTimestamp() bool {
	if o != nil && !common.IsNil(o.Timestamp) {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given time.Time and assigns it to the Timestamp field.
func (o *TopUpConfigurationEventRequest) SetTimestamp(v time.Time) {
	o.Timestamp = &v
}

// GetType returns the Type field value
func (o *TopUpConfigurationEventRequest) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *TopUpConfigurationEventRequest) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *TopUpConfigurationEventRequest) SetType(v string) {
	o.Type = v
}

func (o TopUpConfigurationEventRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TopUpConfigurationEventRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["environment"] = o.Environment
	if !common.IsNil(o.Timestamp) {
		toSerialize["timestamp"] = o.Timestamp
	}
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

type NullableTopUpConfigurationEventRequest struct {
	value *TopUpConfigurationEventRequest
	isSet bool
}

func (v NullableTopUpConfigurationEventRequest) Get() *TopUpConfigurationEventRequest {
	return v.value
}

func (v *NullableTopUpConfigurationEventRequest) Set(val *TopUpConfigurationEventRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTopUpConfigurationEventRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTopUpConfigurationEventRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTopUpConfigurationEventRequest(val *TopUpConfigurationEventRequest) *NullableTopUpConfigurationEventRequest {
	return &NullableTopUpConfigurationEventRequest{value: val, isSet: true}
}

func (v NullableTopUpConfigurationEventRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTopUpConfigurationEventRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (o *TopUpConfigurationEventRequest) isValidType() bool {
	var allowedEnumValues = []string{"balancePlatform.balanceAccount.recurringTopUp.created", "balancePlatform.balanceAccount.recurringTopUp.deleted"}
	for _, allowed := range allowedEnumValues {
		if o.GetType() == allowed {
			return true
		}
	}
	return false
}
