name: Go Models

on: [ workflow_dispatch ]

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate Models
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.18
      - run: make models
      - name: Set PR variables
        id: vars
        run: |
          cd schema
          echo ::set-output name=pr_title::"Update models"
          echo ::set-output name=pr_body::"OpenAPI spec or templates produced new models on $(date +%d-%m-%Y) \
            by [commit](https://github.com/Adyen/adyen-openapi/commit/$(git rev-parse HEAD))."
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38 # v5.0.2
        with:
          token: ${{ secrets.ADYEN_AUTOMATION_BOT_ACCESS_TOKEN }}
          committer: ${{ secrets.ADYEN_AUTOMATION_BOT_EMAIL }}
          author: ${{ secrets.ADYEN_AUTOMATION_BOT_EMAIL }}
          base: develop
          branch: automation/models
          title: ${{ steps.vars.outputs.pr_title }}
          body: ${{ steps.vars.outputs.pr_body }}
          add-paths: |
            src
