name: Prepare release

on:
  workflow_dispatch:
    inputs:
      pre-release:
        required: false
        type: boolean
        default: false
        description: "This release will be labeled as non-production ready"
  push:
    branches:
      - develop

jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Prepare the next main release
        uses: Adyen/release-automation-action@v1.0.0
        with:
          token: ${{ secrets.ADYEN_AUTOMATION_BOT_ACCESS_TOKEN }}
          develop-branch: develop
          release-branch: main
          version-files: src/common/configuration.go
          pre-release: ${{ inputs.pre-release || false }}